client/src/client.rs
json/src/lib.rs

To get this done:
* Remove too many references. It's really inconvenient to prepare a &[Smth<'a>].
One reference is enough to avoid copying.
* Split and fix arguments of `signrawtransaction` and `createrawtransaction`.
I have some code that I'm porting to this, that exercise it, so I'm convinced
that they were wrong before. I'm unsure about the `*withwallet` though.

Add `create_raw_transaction*`

---

.travis.yml
client/examples/test_against_node.rs
client/src/client.rs
client/src/queryable.rs
json/src/lib.rs

Can I suggest this one as an alternative to #11?

Add support for Rust v1.24.0

---

client/src/client.rs

Add address_type for get_new_address to get bech32 addresses directly.

Update get_new_address for Bitcoind 0.16

---

client/Cargo.toml
client/src/client.rs
client/src/lib.rs
client/src/queryable.rs
json/Cargo.toml
json/src/lib.rs

Update Sha256d hashes and use bitcoin_hashes library.

Update rust-bitcoin and use bitcoin hashes new library

---

json/src/lib.rs

Block fields are optional in bitcoin core. If this rpc is used for a transaction that has not been included in a block then it will fail.

Make fields optional in GetRawTransactionResult

---

client/src/client.rs
client/src/error.rs
client/src/queryable.rs
json/Cargo.toml
json/src/getters.rs
json/src/lib.rs

Basically replaces all remaining strings that are actually hex representations of bytes into `Vec<u8>`.

Better handle hex values as bytes

---

client/src/client.rs
json/src/lib.rs

A bunch of fields in getrawtransaction (verbose) are skipped for coinbase txs. They need to be optional.

Fix getrawtransaction for coinbase transactions

---

client/Cargo.toml
client/examples/retry_client.rs
client/examples/test_against_node.rs
client/src/client.rs
client/src/error.rs
json/src/lib.rs

Sorry to put so many changes together, but they are grouped in small commits and too many to open PRs for all of them.
I want to make a new release ASAP because `get_tx_out` is really broken currently and relies on new `jsonrpc` version to be fixed.

Various improvements

---

json/src/lib.rs

Only listtransactions and gettransactions can return negative values,
the others should be u32.

Fix confirmations types

---

client/src/client.rs
json/src/lib.rs

If this is merged, I will release v0.5.0, since this breaks existing interface.

Add fundrawtransaction command, fix signing commands

---

client/src/client.rs

Just prints the only information we have available. (jsonrpc::Client doesn't implement Debug, which is why we didn't just derive it in the first place.)

Have Client implement fmt::Debug

---

client/src/client.rs
json/src/lib.rs

This is a bit more of an invasive change. It's just that a lot of the data between listtransactions and gettransaction overlap but are structured differently.
If you guys don't like the two flattened structs (which make the access feel different then the json structure), let me know. I can make it a simple duplicated struct as well.

 Add listtransactions and restructure gettransaction 

---

client/src/client.rs

This is breaking, but not super urgent for me currently. I'd propose release when we move to rust-bitcoin 0.19.0.

Remove `&[&T]`-like arguments

---

client/Cargo.toml
client/examples/retry_client.rs
client/examples/test_against_node.rs
client/src/lib.rs
json/src/lib.rs

Somehow the build for Rust v1.24 is broken. I don't really understand how. It's unrelated to this PR, though.
Closes https://github.com/rust-bitcoin/rust-bitcoincore-rpc/issues/50.

Export dependent modules used in API

---

json/src/lib.rs

This PR is fixing the field name in the `ListUnspentQueryOptions` - maximum_sum_amount / minimum_sum_amount

Fix minimum_sum_amount field name

---

json/src/lib.rs

From the `importmulti` [documentation](https://bitcoincore.org/en/doc/0.19.0/rpc/wallet/importmulti/):
```
"timestamp": timestamp | "now",   (integer / string, required)
Creation time of the key in seconds since epoch (Jan 1 1970 GMT), or the string "now" to substitute the current synced blockchain time. 
```

Support "now" as importmulti's timestamp parameter

---

client/src/client.rs

- Log failures to send the RPC request. Previously only valid json replies from the server with the `error` field (`RpcError`) were being logged.
- Promote error logging to `Warn`-level messages.
- Demote response logging to `Trace`-level messages.
- Log the requested method name in the response/error log message.
- More compact display for requests, with just the method and params instead of the whole json object. i.e. `getblockhash [176]` instead of `{"jsonrpc":"2.0","id":97,"method":"getblockhash","params":[176]}`
- More compact display for responses, with just the inner `result`. i.e. `7a9b99f78066f22a26c56b2035445285a5a992fc19719c9c27f2255f20f1f2f8` instead of `{"jsonrpc":"2.0","id":97,"error":null,"result":"7a9b99f78066f22a26c56b2035445285a5a992fc19719c9c27f2255f20f1f2f8"}`
I've …

Update logging handling

---

json/src/lib.rs

This field is newly added in 0.20
Fixes https://github.com/rust-bitcoin/rust-bitcoincore-rpc/issues/116.

Add blockheight to wallet transaction responses

---

client/src/error.rs

Otherwise, we get the following deprecation warning from latest Rust:
```
warning: trait objects without an explicit `dyn` are deprecated
--> client/src/error.rs:97:32
|
97 |     fn cause(&self) -> Option<&error::Error> {
|                                ^^^^^^^^^^^^ help: use `dyn`: `dyn error::Error`
|
= note: `#[warn(bare_trait_objects)]` on by default
```

Add explicit 'dyn' to Error::cause() result

---

client/src/client.rs
integration_test/src/main.rs
json/src/lib.rs

Allows to query the bitcoin node's UTXO set for UTXOs belonging to descriptors.

Add scantxoutset

---

integration_test/Cargo.toml
integration_test/src/main.rs
json/Cargo.toml
json/src/lib.rs

Not sure about this crate versioning - should it be also bumped (to 0.12)?

Bump bitcoin dependency to 0.25

---

CHANGELOG.md
README.md
client/Cargo.toml
client/README.md
json/Cargo.toml

With the upgrade of `rust-bitcoin` to `0.25` this crate should upgrade too to be compatible.

Prepare release of v0.12.0

---

json/src/lib.rs

getblock and getblockheader returns -1 as confirmations if the block is not on the main chain

Allow negative confirmations with blocks endpoints

---

.travis.yml
integration_test/run.sh
integration_test/src/main.rs
json/src/lib.rs

As per the changes described in https://bitcoincore.org/en/releases/0.21.0.
v0.21 no longer creates a wallet by default, so we have to create one. I changed the tests to always create a new `testwallet` wallet, let me know if you prefer to only do this for v0.21+.

Compatibility with Bitcoin Core v0.21 

---

client/src/client.rs
integration_test/src/main.rs
json/src/lib.rs

This adds support for the [getchaintips](https://developer.bitcoin.org/reference/rpc/getchaintips.html) RPC returing a list of tips from the blocktree.
Code I used to play around with this:
```Rust
use bitcoincore_rpc::{Auth, Client, RpcApi};
fn main() {
// mainnet rpc port: 8332
// testnet rpc port: 18332
// regtest rpc port: 18444
// signet rpc port: 38332
let rpc = Client::new(
"http://127.0.0.1:8332".to_string(),
Auth::UserPass("your user".to_string(), "your pass".to_string()),
)
.unwrap();
println!("chain tip: {:#?}", rpc.get_chain_tips());
}
```

add: support for getchaintips

---

client/src/client.rs
integration_test/src/main.rs
json/src/lib.rs

Partly addresses https://github.com/rust-bitcoin/rust-bitcoincore-rpc/issues/133
This adds basic support for the `getblocktemplate` RCP to the client. The default 'template' mode, in which Bitcoin Core builds and returns a block template to the RPC client, is implemented. The 'proposal' mode, where the client submits a block to Bitcoin Core for validation (before it's mined; proof-of-work is not checked) as well as longpolling  for changes to a given block template are not implemented yet. However, the basic implementation proposed here can be extended to support both of these features without changing the API.
I've focused on the subset of features (also called "capabilities") that Bitcoin Core actually implements from BIP 22 and BIP 23. I've tested this against mainnet, testnet, regtest …

add: support for getblocktemplate in template mode

---

client/Cargo.toml
client/examples/test_against_node.rs
client/src/client.rs
contrib/test.sh
integration_test/src/main.rs

This is similar to https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/154 but it seems that has stalled. I fixed the "temporary hack" found in #154 as well.
I ran the integration tests against regtest and everything seems to work. Seems like we should get this in so that we can create a tor transport.
My question separately from this PR is where should the work for adding tor transports go? Should it be part of the actual jsonrpc library? Should it be part of this package? or should it be its own package entirely?

updates to newer jsonrpc dependencies containing swappable transports

---

README.md

They didn't match the CI procedure anymore.

Fix MSRV instructions in README

---

json/src/lib.rs

Should fix https://github.com/romanz/electrs/issues/427.

Support 'witness_v1_taproot' in ScriptPubkeyType enum

---

json/src/lib.rs

Following https://github.com/bitcoin/bitcoin/pull/21934, latest Bitcoin Core `getblockchaininfo` RPC does not return the `threshold` and `possible` keys after a softwork is locked in:
```
$ bitcoin-cli getblockchaininfo | jq .softforks.taproot
{
"type": "bip9",
"bip9": {
"status": "locked_in",
"bit": 2,
"start_time": 1619222400,
"timeout": 1628640000,
"since": 687456,
"statistics": {
"period": 2016,
"elapsed": 1721,
"count": 1718
},
"min_activation_height": 709632
},
"active": false
}
```

Make 'threshold' and 'possible' BIP9 statistics optional

---

client/src/client.rs
integration_test/src/main.rs
json/src/lib.rs

This pull request adds the missing networking RPC calls (cf. [API](https://developer.bitcoin.org/reference/rpc/index.html#network-rpcs)). 
I locally tested the calls in regtest as far as I could, looks like they behave as expected.

Add missing networking RPC calls.

---

client/src/client.rs

I found myself needing this for implementing a custom transport.

Make Auth::get_user_pass() public

---

client/src/client.rs
integration_test/run.sh
integration_test/src/main.rs
json/src/lib.rs

`getblockstats` is available in Bitcoin Core since version `0.17.0` .
> It won't work for some heights with pruning.
> It won't work without -txindex for utxo_size_inc, *fee or *feerate stats.
More info (here)[https://bitcoincore.org/en/doc/0.17.0/rpc/blockchain/getblockstats/]
I'm completely new to Rust and this is my first Rust-PR ever, so please have mercy.

Add RPC call 'getblockstats'

---

CHANGELOG.md
client/Cargo.toml
json/Cargo.toml

Mainly to propagate the new bitcoin version

Release v0.15.0

---

.github/workflows/rust.yml
README.md
client/Cargo.toml
client/src/client.rs
client/src/error.rs
client/src/lib.rs
client/src/queryable.rs
contrib/test.sh
integration_test/Cargo.toml
integration_test/src/main.rs
json/Cargo.toml
json/src/lib.rs

The rust-bitcoin stack is moving to a MSRV of 1.41.1
Do a [reasonably minimal] patch set that enables editon 2018
- Patch 1 - Preparatory cleanup
- Patch 2 - Update CI, README, and test script
- Patch 3 - Run `cargo fix --edition`
- Patch 4 - Enable edition 2018

Enable edition 2018

---

README.md

Remove `.to_string()` conversion of uri in example because the argument type is `&str`.
Copy and pasting the example doesn't work.

Remove String conversion in README example.

---

json/src/lib.rs

* Issue
Currently, get_wallet_info() fails when used with descriptor wallets.
* Cause
Bitcoin Core's getwalletinfo command produces a result which sometimes
includes a field called "keypoololdest".
Currently, default wallets have the key but descriptor wallets do not.
* Solution
Making keypool_oldest optional allows this crate to produce the correct
results when operating with descriptor wallets.

Make pub_keypool_oldest optional

---

client/src/client.rs
integration_test/src/main.rs
json/src/lib.rs

Update `get_tx_out_set_info` to Core 22.0+

---

CHANGELOG.md
client/Cargo.toml
client/src/client.rs
integration_test/Cargo.toml
integration_test/src/main.rs
json/Cargo.toml

This update breaks MSRV 1.29 so cannot be merged until we merge: https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/222
Upgrade `rust-bitcoin` dependency to the newly released version (0.29.0). Includes fixing newly deprecated APIs.
- Patch one does the upgrade
- Patch two bumps the crate version and adds release notes

Upgrade bitcoin dependency

---

client/src/client.rs
client/src/error.rs

I added two methods to submit raw and hex-encoded blocks via RPC calls. 
Submitting blocks works, as tested in regtest mode. However, in case of success it currently yields the `Result`:
```
Err(JsonRpc(Json(Error("invalid type: null, expected a string", line: 0, column: 0))))
```
I think this happens because `submitblock` returns `null` in case of success (see [BIP022](https://github.com/bitcoin/bips/blob/master/bip-0022.mediawiki)). 
Any suggestions how I should handle that?

Add 'submitblock' rpc call

---

client/src/client.rs
client/src/lib.rs

Since `HexIterator` is `Read` we can feed it directly to `consensus_decode`
without the intermediate step of converting the hex string to `Vec<u8>`
Could be applied on other fields, but they are now deserialized with `serde_hex` as `Vec<u8>`, we may consider keeping them `String` and then converting them with `deserialize_hex`

Deserialize hexes without allocating intermediate `Vec<u8>`

---

client/Cargo.toml

Bump our `jsonrpc` dependency to the latest version v0.13.0

Bump `jsonrpc` dependency

---

json/src/lib.rs

PR #163 implemented support for `getblocktemplate`. However, during the implementation the `version_bits_available` HashMap the map fields were switched.
This became apparent during testing against a v0.21.1 Bitcoin Core node, which includes support for the Taproot softfork via the 2nd version bit. Previously, no softfork was defined.
```
$ bitcoin-cli getblocktemplate "{\"rules\": [\"segwit\"]}"
...
"vbavailable": {
"taproot": 2
},
...
```

fix: vbavailable map in GetBlockTemplateResult

---

json/src/lib.rs

Fixes #267. Without this variant, a call to
`client.get_blockchain_info()` likely fails on some versions of
bitcoind where other types of softfork deployments were active.

json: add Other variant to SoftforkType

---

client/src/client.rs
json/src/lib.rs

Adds `importdescriptors` rpc. I've renamed `ImportMultiRescanSince` to `Timestamp` given it is not being used solely for multi rescan anymore.
Feels like `ImportMultiResult` should also be renamed, given it is now used by both `importmulti` and `importdescriptors`. I haven't found a proper name for it though.

Adds importdescriptors

---

client/src/client.rs

I'm implementing an in-memory dummy Bitcoin Core RPC server for testing. Exposing `JsonOutPoint` is necessary in order to implement `lockunspent`, which takes `JsonOutPoint`s instead of `OutPoint`s.

Expose JsonOutPoint

---

json/src/lib.rs

We wound up needing `Deserialize` on `ImportDescriptors` for our mock Bitcoin Core RPC server.

Derive Deserialize on ImportDescriptors

---

integration_test/src/main.rs
json/src/lib.rs

The values returned by get_index_info are optional depending on whether the values txindex=1, blockfilterindex=1, and coinstatsindex=1 are configured in bitcoin.conf.
This causes the library to fail in case any of these indices are not configured.
I closed last pull request due to problems with rebase.

Take all get_index_info rpc call return values as Option<>

---

client/src/client.rs
integration_test/src/main.rs
json/src/lib.rs

closes https://github.com/rust-bitcoin/rust-bitcoincore-rpc/issues/290

Add UnloadWalletResult

---

CHANGELOG.md
client/Cargo.toml
json/Cargo.toml

Add release notes and increase the crate minor version to 0.17.0
Justified because we just bumped the `rust-jsonrpc` minor version.
- Patch 1 updates `rust-jsonrpc` dependency to current version
- Patch 2 does the release

Bump crate version to `v0.17.0`

---

integration_test/src/main.rs
json/src/lib.rs

Currently, when reading a chain field from an rpc response from bitcoind the field is parsed as String. If this is happen to be compared with a `bitcoin::network::constants::Network` a custom parser would need to be created, given bitcoind uses `main` and `test` for mainnet and testnet while `rust-bitcoin` used `bitcoin` and `testnet`.
Creates a custom deserializer based on `Network::from_core_arg` so both can be compared seamlessly

Sets chain to bitcoin::network::constants::Network

---

.github/workflows/rust.yml
CHANGELOG.md
README.md
contrib/test.sh

This would allow us to upgrade the `jsonrpc` dep and get `minreq` support possibly alleviating the need for #276. Also required to use the latest `rust-bitcoin`.

Bump MSRV to 1.48

---

client/Cargo.toml
client/src/client.rs
contrib/test.sh

I was running into an confusing issue where a cookie file that worked with `bitcoin-cli` wasn't working with rust-bitcoincore-rpc. It turned out that the cookie file contained a newline, which Bitcoin Core ignored but `rust-bitcoincore-rpc` included as part of the password.
This PR reproduces the behavior of Bitcoin Core, so that all cookie files that with Bitcoin Core should work with `rust-bitcoincore-rpc`.
The commit message:
Bitcoin Core uses a single call to std::getline to read the contents of cookie files, making it ignore newlines in the file, as well as ignore any lines after the first. This reproduces that behavior, so that all cookie files that work with Bitcoin Core should work with this library.

Reproduce Bitcoin Core's handling of cookie files

---

CHANGELOG.md
client/Cargo.toml
client/src/client.rs
client/src/error.rs
client/src/lib.rs
integration_test/Cargo.toml
integration_test/src/main.rs
json/Cargo.toml
json/src/lib.rs

I'm not sure what we want to consider for merge before cutting the next release but at least we need:
- #312 
- #311

Tracking PR for release `0.18.0`

---

client/Cargo.toml
client/src/client.rs
client/src/error.rs
client/src/lib.rs
integration_test/Cargo.toml
integration_test/src/main.rs
json/Cargo.toml
json/src/lib.rs

Upgrade `rust-bitcoin` dependency to the newly release v0.31.0. This is needed so we can update `bitcoind` and then `rust-miniscript` to use the new `bitcoin` release.

Upgrade bitcoin

---

client/src/client.rs
integration_test/run.sh
integration_test/src/main.rs
json/src/lib.rs

this rpc gives information about the active zmq publishers of bitcoin core
currently `get_zmq_notifications` returns a Vec directly from bitcoind, but a structure like getindexinfo could also be used because the possible values of the "type" field are known

add getzmqnotifications rpc

---

.github/workflows/rust.yml
CHANGELOG.md
README.md
contrib/test.sh
json/Cargo.toml

As we have done for the rest of the ecosystem; bump the MSRV to Rust `v1.56.1` - enables edition 2021.

Bump MSRV to Rust 1.56.1

---

json/src/lib.rs

I think this is potentially a bit of a footgun and deserves some clarification.
`fundrawtransaction` has two different ways to specify fee rate, `fee_rate`, and `feeRate`. From [the docs](https://developer.bitcoin.org/reference/rpc/fundrawtransaction.html):
```
"fee_rate" -  Specify a fee rate in sat/vB.
"feeRate" - Specify a fee rate in BTC/kvB.
```
This is extra confusing because the field in FundRawTransactionOptions is called `fee_rate`, but is serde renamed to camelCase, so becomes `feeRate`.
This PR adds a comment to `FundRawTransactionOptions::fee_rate` clarifying that it's in kvB and not vB, and corresponds to the `feeRate` argument to `fundrawtransaction`.
I actually think it would it would probably be best if the rust field were renamed to `fee_rate_per_kvb`, and manually …

Add comment clarifying fee rate in FundRawTransactionOptions

---

client/src/client.rs
integration_test/Cargo.toml
integration_test/src/main.rs

When attempting to use verify_message() function, using Singature kept leading to InvalidSignature.
As such, we replaced Signature with MessageSignature from bitcoin::sign_message::MessageSignature.
We also noticed that there was a // TODO comment to test verify_message, so we also added a test function and it works with the new MessageSignature.

Replace Signature with Message Signature

---

json/src/lib.rs

We're implementing `get_transaction` for our [dummy Bitcoin RPC server](https://crates.io/crates/test-bitcoincore-rpc), and we need to construct and return a `GetTransactionResultDetail`, but `GetTransactionResultDetail` doesn't implement `Serialize`. This PR derives `Serialize` for `GetTransactionResultDetail`, as well as the types it contains.

Derive serde::Serialize for GetTransactionResultDetail et al

---

client/src/client.rs

Since MSRV is 1.56.1: https://github.com/rust-bitcoin/rust-bitcoincore-rpc#minimum-supported-rust-version-msrv

Use `serde_json::value::to_raw_value` in Client::call()

---

contrib/test.sh

MSRV build just broke because of a bunch of dependencies. I did not investigate why I just found a set of versions that builds.
There are more CI fixes in the wind, this just makes the MSRV job pass because all PRs are currently held up by the failing job.

CI: Fix pinning

---

json/src/lib.rs

We deprecate a variant in `GetPeerInfoResultNetwork` that causes clippy to give a false positive. Adding an attribute on the enum does not quitet it down, just add a module level attribute.
This warning has been here for ever.

Allow deprecated in main lib module

---

json/src/lib.rs

Following https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/353.
Tested on latest bitcoind (https://github.com/bitcoin/bitcoin/commit/2cedb42a928fbf3a1e0e8715e918497cbe64af0d) with latest electrs (https://github.com/romanz/electrs/commit/7773c266d108463202bb4bc271dedfbc0b80673a).

Support multiple warnings in RPC responses

---

Cargo-minimal.lock
Cargo-recent.lock
client/Cargo.toml
client/src/client.rs

Just the last patch, upgrade to the latest `jsonrpc` release.
There are a bunch of changes it the lock files, this is because of the removal of the range dependency in `bitcoind`.

Upgrade `jsonrpc` to version `0.18.0`

---

Cargo-minimal.lock
Cargo-recent.lock
client/Cargo.toml

Recently in `jsonrpc` we added an HTTP client that uses `minreq`. Since we now use a version of `jsonrpc` with this feature we can now use `minreq` here.

Use minreq_http feature of jsonrpc

---

client/Cargo.toml
integration_test/Cargo.toml
json/Cargo.toml

Currently we activate the "bitcoin/rand-std" feature unconditionally in `json`. Some users may not wish to use the bitcoin "rand" feature.
Add a "rand" feature to `json` and `client` and use it to activate "rand-std" in `bitcoin`.
The crates currently have no features, this is the first. In order to be less of a breaking change also add a "default" feature and enable "rand" from "default".

Add "rand" feature
