client/src/client.rs
=>  Impl `send_to_address` 

client/src/client.rs, json/src/lib.rs
This PR adds `signrawtransactionwithkey` (Core 0.17), `testmempoolaccept` (Core 0.17), and `generate`.
=> Add three new methods

client/examples/test_against_node.rs, client/src/client.rs, client/src/queryable.rs
Involves #8: this allows custom clients that implement automatically retrying.
This also helps testing code that depends on a client as it allows for easily implementing a dummy client.
=> Add RpcApi trait to allow different implementations of the API

client/examples/retry_client.rs, json/src/lib.rs
=> Add example for an auto-retry client

CHANGELOG.md, client/Cargo.toml, json/Cargo.toml
Minor release, but breaking because of cookie auth.
=> version v0.5.0

client/src/client.rs
This will have to wait for v0.6.0 to be released.
=> Fix two more sha256d::Hash argument nits

json/src/lib.rs
Fixes https://github.com/rust-bitcoin/rust-bitcoincore-rpc/issues/67.
=> Make two fields in GetMiningInfoResult optional

client/Cargo.toml, client/src/client.rs, client/src/error.rs, client/src/lib.rs, client/src/queryable.rs, json/Cargo.toml, json/src/lib.rs
Did I forget anything? We reaaally need those integration tests :/
=> Update to rust-bitcoin v0.19.1

client/src/client.rs, client/src/error.rs, json/src/lib.rs
This one I made separate from #34 because it needs https://github.com/rust-bitcoin/rust-bitcoin/pull/252/ to actually work. Currently the amount type is really broken and can't do serialization.
=> Fix listunspent

client/src/client.rs
Blocked on rust-bitcoin v0.19: https://github.com/rust-bitcoin/rust-bitcoin/milestone/7
Fixes https://github.com/rust-bitcoin/rust-bitcoincore-rpc/issues/72.
@ciyool could you test if this works for you?
=> Add getbalance

client/Cargo.toml, client/src/client.rs, client/src/error.rs, client/src/queryable.rs, json/Cargo.toml, json/src/lib.rs
Closes https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/83 and https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/80.
=> Bump rust-bitcoin dependency to v0.23

json/src/lib.rs
This apparently changed in Core in current master.
Blocked because not released yet in Core.
=> Change getblockchaininfo softfork format

client/src/client.rs, client/src/error.rs, json/src/lib.rs
* wallet_create_funded_psbt
* get_descriptor_info
* combine_psbt
* derive_addresses
* finalize_psbt
* rescan_blockchain
=> implement new rpc methods

client/src/client.rs
I used github web interface for this, let me know if you prefer a standard MR
=> Update client.rs remove apparently unused generic

.travis.yml, Cargo.toml, integration_test/Cargo.toml, integration_test/run.sh, integration_test/src/main.rs
I apologize for not finishing all methods, I got annoyed at the repetitiveness. Only a few minor calls are missing, they can be added later.
I tried adding a Travis section that tests these, let's see what Travis makes of that.
=> Add an integration test for most methods

client/src/client.rs, json/src/lib.rs
Fixes https://github.com/rust-bitcoin/rust-bitcoincore-rpc/issues/108.
=>  Fix some fields in the GetPeerInfoResult struct 

json/src/lib.rs
=> Fix the GetNetworkInfoResult time_offset field

json/src/lib.rs
Signed-off-by: Gregory Hill <gregorydhill@outlook.com>
=> tx result detail address should be optional

client/src/client.rs, integration_test/src/main.rs, json/src/lib.rs
Documented here: https://bitcoincore.org/en/doc/0.20.0/rpc/wallet/listsinceblock/
=> Implement RpcApi::list_since_block()

.travis.yml, contrib/test.sh, integration_test/src/main.rs, json/src/lib.rs
No longer test the entire matrix of Rust and bitcoind versions.
=> Use less Travis jobs

client/src/client.rs, integration_test/src/main.rs
Fixes https://github.com/rust-bitcoin/rust-bitcoincore-rpc/issues/148.
@chris-belcher does this work for you?
=> Add Client::unlock_unspent_all

README.md
=> Update supported Core versions in README

json/Cargo.toml
Found with [cargo-udeps](https://github.com/est31/cargo-udeps)
=> Remove unused dependency hex

CHANGELOG.md, client/Cargo.toml, integration_test/Cargo.toml, json/Cargo.toml
Closes #194 
Updated changelog and version, hope I didn't forget anything and that it's helpful.
Cherry picked commit from #188
=> Release 0.14.0

client/src/client.rs, integration_test/Cargo.toml, integration_test/src/main.rs, json/Cargo.toml, json/src/lib.rs
Following https://github.com/rust-bitcoin/rust-bitcoin/pull/789.
=> Bump 'bitcoin' crate to 0.28.0

client/src/lib.rs
Saw you merged #257 but figured I would run format all as you mentioned anyway.
https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/257#issuecomment-1326497624
=> cargo +nightly fmt --check --all

client/src/client.rs, integration_test/src/main.rs
This adds support for the verbose version of the getrawmempool RPC.
=> add: getrawmempool RPC verbose = true

json/src/lib.rs
Tested against Bitcoin Core 24.
=> Add AddressType::Bech32m

client/src/client.rs, json/src/lib.rs
I've added getmempoolinfo to the client.
=> Add getmempoolinfo

.github/workflows/rust.yml, client/Cargo.toml, client/src/client.rs, client/src/error.rs, client/src/queryable.rs, integration_test/Cargo.toml, integration_test/src/main.rs, json/Cargo.toml, json/src/lib.rs
~~I temporarily added two crates that must be removed before removing the draft status:~~
* ~~hex crate: because I couldn't quickly figure out how to convert bytes to hex~~
* ~~rand: because it didn't seem to be re-exported anymore~~
about `Address`:
* when parameters:  `Address<NetworkChecked>`
* when return values:  `Address<NetworkUnchecked>`
and updated tests with `assume_checked()` where needed
=> bitcoin 0.29.x -> 0.30.0

Cargo-minimal.lock, Cargo-recent.lock, client/examples/test_against_node.rs, client/src/client.rs, client/src/error.rs, client/src/lib.rs, client/src/queryable.rs, integration_test/Cargo.toml, integration_test/src/main.rs, json/Cargo.toml
Done on top of #348 because I had to pin in the CI script, draft until that goes in.
Depend on the latest release of `rust-bitcoin`.
=> Depend on bitcoin v0.32.0
